/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PwRouteImport } from './routes/pw'
import { Route as PcRouteImport } from './routes/pc'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KodeAksesRouteImport } from './routes/kode-akses'
import { Route as CekStatusRouteImport } from './routes/cek-status'
import { Route as AktivasiRouteImport } from './routes/aktivasi'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as PwIndexRouteImport } from './routes/pw.index'
import { Route as PcIndexRouteImport } from './routes/pc.index'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StatusTicketIdRouteImport } from './routes/status.$ticketId'
import { Route as ReviewSlaRouteImport } from './routes/review.sla'
import { Route as ReviewPeruriRouteImport } from './routes/review.peruri'
import { Route as ReviewInboxRouteImport } from './routes/review.inbox'
import { Route as ReviewAuditLogRouteImport } from './routes/review.audit-log'
import { Route as PwStatusPengajuanRouteImport } from './routes/pw.status-pengajuan'
import { Route as PwDaftarkanRouteImport } from './routes/pw.daftarkan'
import { Route as PcStatusPengajuanRouteImport } from './routes/pc.status-pengajuan'
import { Route as PcDaftarkanRouteImport } from './routes/pc.daftarkan'
import { Route as AktivasiAccessCodeRouteImport } from './routes/aktivasi.$accessCode'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminAccessCodesRouteImport } from './routes/admin.access-codes'
import { Route as OpsActivationIndexRouteImport } from './routes/ops.activation.index'
import { Route as StatusTicketIdRevisiRouteImport } from './routes/status.$ticketId.revisi'
import { Route as ReviewInboxTicketIdRouteImport } from './routes/review.inbox.$ticketId'
import { Route as PwStatusPengajuanTicketIdRouteImport } from './routes/pw.status-pengajuan.$ticketId'
import { Route as PcStatusPengajuanTicketIdRouteImport } from './routes/pc.status-pengajuan.$ticketId'
import { Route as OpsActivationSubmissionsRouteImport } from './routes/ops.activation.submissions'
import { Route as OpsActivationSettingsRouteImport } from './routes/ops.activation.settings'
import { Route as OpsActivationPeruriExportRouteImport } from './routes/ops.activation.peruri-export'
import { Route as OpsActivationAuditLogRouteImport } from './routes/ops.activation.audit-log'
import { Route as OpsActivationAccessCodesRouteImport } from './routes/ops.activation.access-codes'
import { Route as AktivasiSuksesTicketIdRouteImport } from './routes/aktivasi.sukses.$ticketId'
import { Route as PwStatusPengajuanTicketIdRevisiRouteImport } from './routes/pw.status-pengajuan.$ticketId.revisi'
import { Route as PcStatusPengajuanTicketIdRevisiRouteImport } from './routes/pc.status-pengajuan.$ticketId.revisi'
import { Route as OpsActivationSubmissionsTicketIdRouteImport } from './routes/ops.activation.submissions.$ticketId'
import { Route as OpsActivationAccessCodesCodeIdRouteImport } from './routes/ops.activation.access-codes.$codeId'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PwRoute = PwRouteImport.update({
  id: '/pw',
  path: '/pw',
  getParentRoute: () => rootRouteImport,
} as any)
const PcRoute = PcRouteImport.update({
  id: '/pc',
  path: '/pc',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KodeAksesRoute = KodeAksesRouteImport.update({
  id: '/kode-akses',
  path: '/kode-akses',
  getParentRoute: () => rootRouteImport,
} as any)
const CekStatusRoute = CekStatusRouteImport.update({
  id: '/cek-status',
  path: '/cek-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AktivasiRoute = AktivasiRouteImport.update({
  id: '/aktivasi',
  path: '/aktivasi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewRoute,
} as any)
const PwIndexRoute = PwIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PwRoute,
} as any)
const PcIndexRoute = PcIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PcRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StatusTicketIdRoute = StatusTicketIdRouteImport.update({
  id: '/status/$ticketId',
  path: '/status/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewSlaRoute = ReviewSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewPeruriRoute = ReviewPeruriRouteImport.update({
  id: '/peruri',
  path: '/peruri',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewInboxRoute = ReviewInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewAuditLogRoute = ReviewAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => ReviewRoute,
} as any)
const PwStatusPengajuanRoute = PwStatusPengajuanRouteImport.update({
  id: '/status-pengajuan',
  path: '/status-pengajuan',
  getParentRoute: () => PwRoute,
} as any)
const PwDaftarkanRoute = PwDaftarkanRouteImport.update({
  id: '/daftarkan',
  path: '/daftarkan',
  getParentRoute: () => PwRoute,
} as any)
const PcStatusPengajuanRoute = PcStatusPengajuanRouteImport.update({
  id: '/status-pengajuan',
  path: '/status-pengajuan',
  getParentRoute: () => PcRoute,
} as any)
const PcDaftarkanRoute = PcDaftarkanRouteImport.update({
  id: '/daftarkan',
  path: '/daftarkan',
  getParentRoute: () => PcRoute,
} as any)
const AktivasiAccessCodeRoute = AktivasiAccessCodeRouteImport.update({
  id: '/$accessCode',
  path: '/$accessCode',
  getParentRoute: () => AktivasiRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessCodesRoute = AdminAccessCodesRouteImport.update({
  id: '/access-codes',
  path: '/access-codes',
  getParentRoute: () => AdminRoute,
} as any)
const OpsActivationIndexRoute = OpsActivationIndexRouteImport.update({
  id: '/activation/',
  path: '/activation/',
  getParentRoute: () => OpsRoute,
} as any)
const StatusTicketIdRevisiRoute = StatusTicketIdRevisiRouteImport.update({
  id: '/revisi',
  path: '/revisi',
  getParentRoute: () => StatusTicketIdRoute,
} as any)
const ReviewInboxTicketIdRoute = ReviewInboxTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => ReviewInboxRoute,
} as any)
const PwStatusPengajuanTicketIdRoute =
  PwStatusPengajuanTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => PwStatusPengajuanRoute,
  } as any)
const PcStatusPengajuanTicketIdRoute =
  PcStatusPengajuanTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => PcStatusPengajuanRoute,
  } as any)
const OpsActivationSubmissionsRoute =
  OpsActivationSubmissionsRouteImport.update({
    id: '/activation/submissions',
    path: '/activation/submissions',
    getParentRoute: () => OpsRoute,
  } as any)
const OpsActivationSettingsRoute = OpsActivationSettingsRouteImport.update({
  id: '/activation/settings',
  path: '/activation/settings',
  getParentRoute: () => OpsRoute,
} as any)
const OpsActivationPeruriExportRoute =
  OpsActivationPeruriExportRouteImport.update({
    id: '/activation/peruri-export',
    path: '/activation/peruri-export',
    getParentRoute: () => OpsRoute,
  } as any)
const OpsActivationAuditLogRoute = OpsActivationAuditLogRouteImport.update({
  id: '/activation/audit-log',
  path: '/activation/audit-log',
  getParentRoute: () => OpsRoute,
} as any)
const OpsActivationAccessCodesRoute =
  OpsActivationAccessCodesRouteImport.update({
    id: '/activation/access-codes',
    path: '/activation/access-codes',
    getParentRoute: () => OpsRoute,
  } as any)
const AktivasiSuksesTicketIdRoute = AktivasiSuksesTicketIdRouteImport.update({
  id: '/sukses/$ticketId',
  path: '/sukses/$ticketId',
  getParentRoute: () => AktivasiRoute,
} as any)
const PwStatusPengajuanTicketIdRevisiRoute =
  PwStatusPengajuanTicketIdRevisiRouteImport.update({
    id: '/revisi',
    path: '/revisi',
    getParentRoute: () => PwStatusPengajuanTicketIdRoute,
  } as any)
const PcStatusPengajuanTicketIdRevisiRoute =
  PcStatusPengajuanTicketIdRevisiRouteImport.update({
    id: '/revisi',
    path: '/revisi',
    getParentRoute: () => PcStatusPengajuanTicketIdRoute,
  } as any)
const OpsActivationSubmissionsTicketIdRoute =
  OpsActivationSubmissionsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => OpsActivationSubmissionsRoute,
  } as any)
const OpsActivationAccessCodesCodeIdRoute =
  OpsActivationAccessCodesCodeIdRouteImport.update({
    id: '/$codeId',
    path: '/$codeId',
    getParentRoute: () => OpsActivationAccessCodesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aktivasi': typeof AktivasiRouteWithChildren
  '/cek-status': typeof CekStatusRoute
  '/kode-akses': typeof KodeAksesRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/pc': typeof PcRouteWithChildren
  '/pw': typeof PwRouteWithChildren
  '/review': typeof ReviewRouteWithChildren
  '/admin/access-codes': typeof AdminAccessCodesRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/aktivasi/$accessCode': typeof AktivasiAccessCodeRoute
  '/pc/daftarkan': typeof PcDaftarkanRoute
  '/pc/status-pengajuan': typeof PcStatusPengajuanRouteWithChildren
  '/pw/daftarkan': typeof PwDaftarkanRoute
  '/pw/status-pengajuan': typeof PwStatusPengajuanRouteWithChildren
  '/review/audit-log': typeof ReviewAuditLogRoute
  '/review/inbox': typeof ReviewInboxRouteWithChildren
  '/review/peruri': typeof ReviewPeruriRoute
  '/review/sla': typeof ReviewSlaRoute
  '/status/$ticketId': typeof StatusTicketIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/pc/': typeof PcIndexRoute
  '/pw/': typeof PwIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/aktivasi/sukses/$ticketId': typeof AktivasiSuksesTicketIdRoute
  '/ops/activation/access-codes': typeof OpsActivationAccessCodesRouteWithChildren
  '/ops/activation/audit-log': typeof OpsActivationAuditLogRoute
  '/ops/activation/peruri-export': typeof OpsActivationPeruriExportRoute
  '/ops/activation/settings': typeof OpsActivationSettingsRoute
  '/ops/activation/submissions': typeof OpsActivationSubmissionsRouteWithChildren
  '/pc/status-pengajuan/$ticketId': typeof PcStatusPengajuanTicketIdRouteWithChildren
  '/pw/status-pengajuan/$ticketId': typeof PwStatusPengajuanTicketIdRouteWithChildren
  '/review/inbox/$ticketId': typeof ReviewInboxTicketIdRoute
  '/status/$ticketId/revisi': typeof StatusTicketIdRevisiRoute
  '/ops/activation/': typeof OpsActivationIndexRoute
  '/ops/activation/access-codes/$codeId': typeof OpsActivationAccessCodesCodeIdRoute
  '/ops/activation/submissions/$ticketId': typeof OpsActivationSubmissionsTicketIdRoute
  '/pc/status-pengajuan/$ticketId/revisi': typeof PcStatusPengajuanTicketIdRevisiRoute
  '/pw/status-pengajuan/$ticketId/revisi': typeof PwStatusPengajuanTicketIdRevisiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aktivasi': typeof AktivasiRouteWithChildren
  '/cek-status': typeof CekStatusRoute
  '/kode-akses': typeof KodeAksesRoute
  '/login': typeof LoginRoute
  '/admin/access-codes': typeof AdminAccessCodesRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/aktivasi/$accessCode': typeof AktivasiAccessCodeRoute
  '/pc/daftarkan': typeof PcDaftarkanRoute
  '/pc/status-pengajuan': typeof PcStatusPengajuanRouteWithChildren
  '/pw/daftarkan': typeof PwDaftarkanRoute
  '/pw/status-pengajuan': typeof PwStatusPengajuanRouteWithChildren
  '/review/audit-log': typeof ReviewAuditLogRoute
  '/review/inbox': typeof ReviewInboxRouteWithChildren
  '/review/peruri': typeof ReviewPeruriRoute
  '/review/sla': typeof ReviewSlaRoute
  '/status/$ticketId': typeof StatusTicketIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/ops': typeof OpsIndexRoute
  '/pc': typeof PcIndexRoute
  '/pw': typeof PwIndexRoute
  '/review': typeof ReviewIndexRoute
  '/aktivasi/sukses/$ticketId': typeof AktivasiSuksesTicketIdRoute
  '/ops/activation/access-codes': typeof OpsActivationAccessCodesRouteWithChildren
  '/ops/activation/audit-log': typeof OpsActivationAuditLogRoute
  '/ops/activation/peruri-export': typeof OpsActivationPeruriExportRoute
  '/ops/activation/settings': typeof OpsActivationSettingsRoute
  '/ops/activation/submissions': typeof OpsActivationSubmissionsRouteWithChildren
  '/pc/status-pengajuan/$ticketId': typeof PcStatusPengajuanTicketIdRouteWithChildren
  '/pw/status-pengajuan/$ticketId': typeof PwStatusPengajuanTicketIdRouteWithChildren
  '/review/inbox/$ticketId': typeof ReviewInboxTicketIdRoute
  '/status/$ticketId/revisi': typeof StatusTicketIdRevisiRoute
  '/ops/activation': typeof OpsActivationIndexRoute
  '/ops/activation/access-codes/$codeId': typeof OpsActivationAccessCodesCodeIdRoute
  '/ops/activation/submissions/$ticketId': typeof OpsActivationSubmissionsTicketIdRoute
  '/pc/status-pengajuan/$ticketId/revisi': typeof PcStatusPengajuanTicketIdRevisiRoute
  '/pw/status-pengajuan/$ticketId/revisi': typeof PwStatusPengajuanTicketIdRevisiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aktivasi': typeof AktivasiRouteWithChildren
  '/cek-status': typeof CekStatusRoute
  '/kode-akses': typeof KodeAksesRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/pc': typeof PcRouteWithChildren
  '/pw': typeof PwRouteWithChildren
  '/review': typeof ReviewRouteWithChildren
  '/admin/access-codes': typeof AdminAccessCodesRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/aktivasi/$accessCode': typeof AktivasiAccessCodeRoute
  '/pc/daftarkan': typeof PcDaftarkanRoute
  '/pc/status-pengajuan': typeof PcStatusPengajuanRouteWithChildren
  '/pw/daftarkan': typeof PwDaftarkanRoute
  '/pw/status-pengajuan': typeof PwStatusPengajuanRouteWithChildren
  '/review/audit-log': typeof ReviewAuditLogRoute
  '/review/inbox': typeof ReviewInboxRouteWithChildren
  '/review/peruri': typeof ReviewPeruriRoute
  '/review/sla': typeof ReviewSlaRoute
  '/status/$ticketId': typeof StatusTicketIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/pc/': typeof PcIndexRoute
  '/pw/': typeof PwIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/aktivasi/sukses/$ticketId': typeof AktivasiSuksesTicketIdRoute
  '/ops/activation/access-codes': typeof OpsActivationAccessCodesRouteWithChildren
  '/ops/activation/audit-log': typeof OpsActivationAuditLogRoute
  '/ops/activation/peruri-export': typeof OpsActivationPeruriExportRoute
  '/ops/activation/settings': typeof OpsActivationSettingsRoute
  '/ops/activation/submissions': typeof OpsActivationSubmissionsRouteWithChildren
  '/pc/status-pengajuan/$ticketId': typeof PcStatusPengajuanTicketIdRouteWithChildren
  '/pw/status-pengajuan/$ticketId': typeof PwStatusPengajuanTicketIdRouteWithChildren
  '/review/inbox/$ticketId': typeof ReviewInboxTicketIdRoute
  '/status/$ticketId/revisi': typeof StatusTicketIdRevisiRoute
  '/ops/activation/': typeof OpsActivationIndexRoute
  '/ops/activation/access-codes/$codeId': typeof OpsActivationAccessCodesCodeIdRoute
  '/ops/activation/submissions/$ticketId': typeof OpsActivationSubmissionsTicketIdRoute
  '/pc/status-pengajuan/$ticketId/revisi': typeof PcStatusPengajuanTicketIdRevisiRoute
  '/pw/status-pengajuan/$ticketId/revisi': typeof PwStatusPengajuanTicketIdRevisiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aktivasi'
    | '/cek-status'
    | '/kode-akses'
    | '/login'
    | '/ops'
    | '/pc'
    | '/pw'
    | '/review'
    | '/admin/access-codes'
    | '/admin/audit-log'
    | '/admin/settings'
    | '/aktivasi/$accessCode'
    | '/pc/daftarkan'
    | '/pc/status-pengajuan'
    | '/pw/daftarkan'
    | '/pw/status-pengajuan'
    | '/review/audit-log'
    | '/review/inbox'
    | '/review/peruri'
    | '/review/sla'
    | '/status/$ticketId'
    | '/admin/'
    | '/ops/'
    | '/pc/'
    | '/pw/'
    | '/review/'
    | '/aktivasi/sukses/$ticketId'
    | '/ops/activation/access-codes'
    | '/ops/activation/audit-log'
    | '/ops/activation/peruri-export'
    | '/ops/activation/settings'
    | '/ops/activation/submissions'
    | '/pc/status-pengajuan/$ticketId'
    | '/pw/status-pengajuan/$ticketId'
    | '/review/inbox/$ticketId'
    | '/status/$ticketId/revisi'
    | '/ops/activation/'
    | '/ops/activation/access-codes/$codeId'
    | '/ops/activation/submissions/$ticketId'
    | '/pc/status-pengajuan/$ticketId/revisi'
    | '/pw/status-pengajuan/$ticketId/revisi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aktivasi'
    | '/cek-status'
    | '/kode-akses'
    | '/login'
    | '/admin/access-codes'
    | '/admin/audit-log'
    | '/admin/settings'
    | '/aktivasi/$accessCode'
    | '/pc/daftarkan'
    | '/pc/status-pengajuan'
    | '/pw/daftarkan'
    | '/pw/status-pengajuan'
    | '/review/audit-log'
    | '/review/inbox'
    | '/review/peruri'
    | '/review/sla'
    | '/status/$ticketId'
    | '/admin'
    | '/ops'
    | '/pc'
    | '/pw'
    | '/review'
    | '/aktivasi/sukses/$ticketId'
    | '/ops/activation/access-codes'
    | '/ops/activation/audit-log'
    | '/ops/activation/peruri-export'
    | '/ops/activation/settings'
    | '/ops/activation/submissions'
    | '/pc/status-pengajuan/$ticketId'
    | '/pw/status-pengajuan/$ticketId'
    | '/review/inbox/$ticketId'
    | '/status/$ticketId/revisi'
    | '/ops/activation'
    | '/ops/activation/access-codes/$codeId'
    | '/ops/activation/submissions/$ticketId'
    | '/pc/status-pengajuan/$ticketId/revisi'
    | '/pw/status-pengajuan/$ticketId/revisi'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aktivasi'
    | '/cek-status'
    | '/kode-akses'
    | '/login'
    | '/ops'
    | '/pc'
    | '/pw'
    | '/review'
    | '/admin/access-codes'
    | '/admin/audit-log'
    | '/admin/settings'
    | '/aktivasi/$accessCode'
    | '/pc/daftarkan'
    | '/pc/status-pengajuan'
    | '/pw/daftarkan'
    | '/pw/status-pengajuan'
    | '/review/audit-log'
    | '/review/inbox'
    | '/review/peruri'
    | '/review/sla'
    | '/status/$ticketId'
    | '/admin/'
    | '/ops/'
    | '/pc/'
    | '/pw/'
    | '/review/'
    | '/aktivasi/sukses/$ticketId'
    | '/ops/activation/access-codes'
    | '/ops/activation/audit-log'
    | '/ops/activation/peruri-export'
    | '/ops/activation/settings'
    | '/ops/activation/submissions'
    | '/pc/status-pengajuan/$ticketId'
    | '/pw/status-pengajuan/$ticketId'
    | '/review/inbox/$ticketId'
    | '/status/$ticketId/revisi'
    | '/ops/activation/'
    | '/ops/activation/access-codes/$codeId'
    | '/ops/activation/submissions/$ticketId'
    | '/pc/status-pengajuan/$ticketId/revisi'
    | '/pw/status-pengajuan/$ticketId/revisi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AktivasiRoute: typeof AktivasiRouteWithChildren
  CekStatusRoute: typeof CekStatusRoute
  KodeAksesRoute: typeof KodeAksesRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRouteWithChildren
  PcRoute: typeof PcRouteWithChildren
  PwRoute: typeof PwRouteWithChildren
  ReviewRoute: typeof ReviewRouteWithChildren
  StatusTicketIdRoute: typeof StatusTicketIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pw': {
      id: '/pw'
      path: '/pw'
      fullPath: '/pw'
      preLoaderRoute: typeof PwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pc': {
      id: '/pc'
      path: '/pc'
      fullPath: '/pc'
      preLoaderRoute: typeof PcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kode-akses': {
      id: '/kode-akses'
      path: '/kode-akses'
      fullPath: '/kode-akses'
      preLoaderRoute: typeof KodeAksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cek-status': {
      id: '/cek-status'
      path: '/cek-status'
      fullPath: '/cek-status'
      preLoaderRoute: typeof CekStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivasi': {
      id: '/aktivasi'
      path: '/aktivasi'
      fullPath: '/aktivasi'
      preLoaderRoute: typeof AktivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/pw/': {
      id: '/pw/'
      path: '/'
      fullPath: '/pw/'
      preLoaderRoute: typeof PwIndexRouteImport
      parentRoute: typeof PwRoute
    }
    '/pc/': {
      id: '/pc/'
      path: '/'
      fullPath: '/pc/'
      preLoaderRoute: typeof PcIndexRouteImport
      parentRoute: typeof PcRoute
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/status/$ticketId': {
      id: '/status/$ticketId'
      path: '/status/$ticketId'
      fullPath: '/status/$ticketId'
      preLoaderRoute: typeof StatusTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/sla': {
      id: '/review/sla'
      path: '/sla'
      fullPath: '/review/sla'
      preLoaderRoute: typeof ReviewSlaRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/peruri': {
      id: '/review/peruri'
      path: '/peruri'
      fullPath: '/review/peruri'
      preLoaderRoute: typeof ReviewPeruriRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/inbox': {
      id: '/review/inbox'
      path: '/inbox'
      fullPath: '/review/inbox'
      preLoaderRoute: typeof ReviewInboxRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/audit-log': {
      id: '/review/audit-log'
      path: '/audit-log'
      fullPath: '/review/audit-log'
      preLoaderRoute: typeof ReviewAuditLogRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/pw/status-pengajuan': {
      id: '/pw/status-pengajuan'
      path: '/status-pengajuan'
      fullPath: '/pw/status-pengajuan'
      preLoaderRoute: typeof PwStatusPengajuanRouteImport
      parentRoute: typeof PwRoute
    }
    '/pw/daftarkan': {
      id: '/pw/daftarkan'
      path: '/daftarkan'
      fullPath: '/pw/daftarkan'
      preLoaderRoute: typeof PwDaftarkanRouteImport
      parentRoute: typeof PwRoute
    }
    '/pc/status-pengajuan': {
      id: '/pc/status-pengajuan'
      path: '/status-pengajuan'
      fullPath: '/pc/status-pengajuan'
      preLoaderRoute: typeof PcStatusPengajuanRouteImport
      parentRoute: typeof PcRoute
    }
    '/pc/daftarkan': {
      id: '/pc/daftarkan'
      path: '/daftarkan'
      fullPath: '/pc/daftarkan'
      preLoaderRoute: typeof PcDaftarkanRouteImport
      parentRoute: typeof PcRoute
    }
    '/aktivasi/$accessCode': {
      id: '/aktivasi/$accessCode'
      path: '/$accessCode'
      fullPath: '/aktivasi/$accessCode'
      preLoaderRoute: typeof AktivasiAccessCodeRouteImport
      parentRoute: typeof AktivasiRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access-codes': {
      id: '/admin/access-codes'
      path: '/access-codes'
      fullPath: '/admin/access-codes'
      preLoaderRoute: typeof AdminAccessCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ops/activation/': {
      id: '/ops/activation/'
      path: '/activation'
      fullPath: '/ops/activation/'
      preLoaderRoute: typeof OpsActivationIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/status/$ticketId/revisi': {
      id: '/status/$ticketId/revisi'
      path: '/revisi'
      fullPath: '/status/$ticketId/revisi'
      preLoaderRoute: typeof StatusTicketIdRevisiRouteImport
      parentRoute: typeof StatusTicketIdRoute
    }
    '/review/inbox/$ticketId': {
      id: '/review/inbox/$ticketId'
      path: '/$ticketId'
      fullPath: '/review/inbox/$ticketId'
      preLoaderRoute: typeof ReviewInboxTicketIdRouteImport
      parentRoute: typeof ReviewInboxRoute
    }
    '/pw/status-pengajuan/$ticketId': {
      id: '/pw/status-pengajuan/$ticketId'
      path: '/$ticketId'
      fullPath: '/pw/status-pengajuan/$ticketId'
      preLoaderRoute: typeof PwStatusPengajuanTicketIdRouteImport
      parentRoute: typeof PwStatusPengajuanRoute
    }
    '/pc/status-pengajuan/$ticketId': {
      id: '/pc/status-pengajuan/$ticketId'
      path: '/$ticketId'
      fullPath: '/pc/status-pengajuan/$ticketId'
      preLoaderRoute: typeof PcStatusPengajuanTicketIdRouteImport
      parentRoute: typeof PcStatusPengajuanRoute
    }
    '/ops/activation/submissions': {
      id: '/ops/activation/submissions'
      path: '/activation/submissions'
      fullPath: '/ops/activation/submissions'
      preLoaderRoute: typeof OpsActivationSubmissionsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/activation/settings': {
      id: '/ops/activation/settings'
      path: '/activation/settings'
      fullPath: '/ops/activation/settings'
      preLoaderRoute: typeof OpsActivationSettingsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/activation/peruri-export': {
      id: '/ops/activation/peruri-export'
      path: '/activation/peruri-export'
      fullPath: '/ops/activation/peruri-export'
      preLoaderRoute: typeof OpsActivationPeruriExportRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/activation/audit-log': {
      id: '/ops/activation/audit-log'
      path: '/activation/audit-log'
      fullPath: '/ops/activation/audit-log'
      preLoaderRoute: typeof OpsActivationAuditLogRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/activation/access-codes': {
      id: '/ops/activation/access-codes'
      path: '/activation/access-codes'
      fullPath: '/ops/activation/access-codes'
      preLoaderRoute: typeof OpsActivationAccessCodesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/aktivasi/sukses/$ticketId': {
      id: '/aktivasi/sukses/$ticketId'
      path: '/sukses/$ticketId'
      fullPath: '/aktivasi/sukses/$ticketId'
      preLoaderRoute: typeof AktivasiSuksesTicketIdRouteImport
      parentRoute: typeof AktivasiRoute
    }
    '/pw/status-pengajuan/$ticketId/revisi': {
      id: '/pw/status-pengajuan/$ticketId/revisi'
      path: '/revisi'
      fullPath: '/pw/status-pengajuan/$ticketId/revisi'
      preLoaderRoute: typeof PwStatusPengajuanTicketIdRevisiRouteImport
      parentRoute: typeof PwStatusPengajuanTicketIdRoute
    }
    '/pc/status-pengajuan/$ticketId/revisi': {
      id: '/pc/status-pengajuan/$ticketId/revisi'
      path: '/revisi'
      fullPath: '/pc/status-pengajuan/$ticketId/revisi'
      preLoaderRoute: typeof PcStatusPengajuanTicketIdRevisiRouteImport
      parentRoute: typeof PcStatusPengajuanTicketIdRoute
    }
    '/ops/activation/submissions/$ticketId': {
      id: '/ops/activation/submissions/$ticketId'
      path: '/$ticketId'
      fullPath: '/ops/activation/submissions/$ticketId'
      preLoaderRoute: typeof OpsActivationSubmissionsTicketIdRouteImport
      parentRoute: typeof OpsActivationSubmissionsRoute
    }
    '/ops/activation/access-codes/$codeId': {
      id: '/ops/activation/access-codes/$codeId'
      path: '/$codeId'
      fullPath: '/ops/activation/access-codes/$codeId'
      preLoaderRoute: typeof OpsActivationAccessCodesCodeIdRouteImport
      parentRoute: typeof OpsActivationAccessCodesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccessCodesRoute: typeof AdminAccessCodesRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessCodesRoute: AdminAccessCodesRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AktivasiRouteChildren {
  AktivasiAccessCodeRoute: typeof AktivasiAccessCodeRoute
  AktivasiSuksesTicketIdRoute: typeof AktivasiSuksesTicketIdRoute
}

const AktivasiRouteChildren: AktivasiRouteChildren = {
  AktivasiAccessCodeRoute: AktivasiAccessCodeRoute,
  AktivasiSuksesTicketIdRoute: AktivasiSuksesTicketIdRoute,
}

const AktivasiRouteWithChildren = AktivasiRoute._addFileChildren(
  AktivasiRouteChildren,
)

interface OpsActivationAccessCodesRouteChildren {
  OpsActivationAccessCodesCodeIdRoute: typeof OpsActivationAccessCodesCodeIdRoute
}

const OpsActivationAccessCodesRouteChildren: OpsActivationAccessCodesRouteChildren =
  {
    OpsActivationAccessCodesCodeIdRoute: OpsActivationAccessCodesCodeIdRoute,
  }

const OpsActivationAccessCodesRouteWithChildren =
  OpsActivationAccessCodesRoute._addFileChildren(
    OpsActivationAccessCodesRouteChildren,
  )

interface OpsActivationSubmissionsRouteChildren {
  OpsActivationSubmissionsTicketIdRoute: typeof OpsActivationSubmissionsTicketIdRoute
}

const OpsActivationSubmissionsRouteChildren: OpsActivationSubmissionsRouteChildren =
  {
    OpsActivationSubmissionsTicketIdRoute:
      OpsActivationSubmissionsTicketIdRoute,
  }

const OpsActivationSubmissionsRouteWithChildren =
  OpsActivationSubmissionsRoute._addFileChildren(
    OpsActivationSubmissionsRouteChildren,
  )

interface OpsRouteChildren {
  OpsIndexRoute: typeof OpsIndexRoute
  OpsActivationAccessCodesRoute: typeof OpsActivationAccessCodesRouteWithChildren
  OpsActivationAuditLogRoute: typeof OpsActivationAuditLogRoute
  OpsActivationPeruriExportRoute: typeof OpsActivationPeruriExportRoute
  OpsActivationSettingsRoute: typeof OpsActivationSettingsRoute
  OpsActivationSubmissionsRoute: typeof OpsActivationSubmissionsRouteWithChildren
  OpsActivationIndexRoute: typeof OpsActivationIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsIndexRoute: OpsIndexRoute,
  OpsActivationAccessCodesRoute: OpsActivationAccessCodesRouteWithChildren,
  OpsActivationAuditLogRoute: OpsActivationAuditLogRoute,
  OpsActivationPeruriExportRoute: OpsActivationPeruriExportRoute,
  OpsActivationSettingsRoute: OpsActivationSettingsRoute,
  OpsActivationSubmissionsRoute: OpsActivationSubmissionsRouteWithChildren,
  OpsActivationIndexRoute: OpsActivationIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

interface PcStatusPengajuanTicketIdRouteChildren {
  PcStatusPengajuanTicketIdRevisiRoute: typeof PcStatusPengajuanTicketIdRevisiRoute
}

const PcStatusPengajuanTicketIdRouteChildren: PcStatusPengajuanTicketIdRouteChildren =
  {
    PcStatusPengajuanTicketIdRevisiRoute: PcStatusPengajuanTicketIdRevisiRoute,
  }

const PcStatusPengajuanTicketIdRouteWithChildren =
  PcStatusPengajuanTicketIdRoute._addFileChildren(
    PcStatusPengajuanTicketIdRouteChildren,
  )

interface PcStatusPengajuanRouteChildren {
  PcStatusPengajuanTicketIdRoute: typeof PcStatusPengajuanTicketIdRouteWithChildren
}

const PcStatusPengajuanRouteChildren: PcStatusPengajuanRouteChildren = {
  PcStatusPengajuanTicketIdRoute: PcStatusPengajuanTicketIdRouteWithChildren,
}

const PcStatusPengajuanRouteWithChildren =
  PcStatusPengajuanRoute._addFileChildren(PcStatusPengajuanRouteChildren)

interface PcRouteChildren {
  PcDaftarkanRoute: typeof PcDaftarkanRoute
  PcStatusPengajuanRoute: typeof PcStatusPengajuanRouteWithChildren
  PcIndexRoute: typeof PcIndexRoute
}

const PcRouteChildren: PcRouteChildren = {
  PcDaftarkanRoute: PcDaftarkanRoute,
  PcStatusPengajuanRoute: PcStatusPengajuanRouteWithChildren,
  PcIndexRoute: PcIndexRoute,
}

const PcRouteWithChildren = PcRoute._addFileChildren(PcRouteChildren)

interface PwStatusPengajuanTicketIdRouteChildren {
  PwStatusPengajuanTicketIdRevisiRoute: typeof PwStatusPengajuanTicketIdRevisiRoute
}

const PwStatusPengajuanTicketIdRouteChildren: PwStatusPengajuanTicketIdRouteChildren =
  {
    PwStatusPengajuanTicketIdRevisiRoute: PwStatusPengajuanTicketIdRevisiRoute,
  }

const PwStatusPengajuanTicketIdRouteWithChildren =
  PwStatusPengajuanTicketIdRoute._addFileChildren(
    PwStatusPengajuanTicketIdRouteChildren,
  )

interface PwStatusPengajuanRouteChildren {
  PwStatusPengajuanTicketIdRoute: typeof PwStatusPengajuanTicketIdRouteWithChildren
}

const PwStatusPengajuanRouteChildren: PwStatusPengajuanRouteChildren = {
  PwStatusPengajuanTicketIdRoute: PwStatusPengajuanTicketIdRouteWithChildren,
}

const PwStatusPengajuanRouteWithChildren =
  PwStatusPengajuanRoute._addFileChildren(PwStatusPengajuanRouteChildren)

interface PwRouteChildren {
  PwDaftarkanRoute: typeof PwDaftarkanRoute
  PwStatusPengajuanRoute: typeof PwStatusPengajuanRouteWithChildren
  PwIndexRoute: typeof PwIndexRoute
}

const PwRouteChildren: PwRouteChildren = {
  PwDaftarkanRoute: PwDaftarkanRoute,
  PwStatusPengajuanRoute: PwStatusPengajuanRouteWithChildren,
  PwIndexRoute: PwIndexRoute,
}

const PwRouteWithChildren = PwRoute._addFileChildren(PwRouteChildren)

interface ReviewInboxRouteChildren {
  ReviewInboxTicketIdRoute: typeof ReviewInboxTicketIdRoute
}

const ReviewInboxRouteChildren: ReviewInboxRouteChildren = {
  ReviewInboxTicketIdRoute: ReviewInboxTicketIdRoute,
}

const ReviewInboxRouteWithChildren = ReviewInboxRoute._addFileChildren(
  ReviewInboxRouteChildren,
)

interface ReviewRouteChildren {
  ReviewAuditLogRoute: typeof ReviewAuditLogRoute
  ReviewInboxRoute: typeof ReviewInboxRouteWithChildren
  ReviewPeruriRoute: typeof ReviewPeruriRoute
  ReviewSlaRoute: typeof ReviewSlaRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewAuditLogRoute: ReviewAuditLogRoute,
  ReviewInboxRoute: ReviewInboxRouteWithChildren,
  ReviewPeruriRoute: ReviewPeruriRoute,
  ReviewSlaRoute: ReviewSlaRoute,
  ReviewIndexRoute: ReviewIndexRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

interface StatusTicketIdRouteChildren {
  StatusTicketIdRevisiRoute: typeof StatusTicketIdRevisiRoute
}

const StatusTicketIdRouteChildren: StatusTicketIdRouteChildren = {
  StatusTicketIdRevisiRoute: StatusTicketIdRevisiRoute,
}

const StatusTicketIdRouteWithChildren = StatusTicketIdRoute._addFileChildren(
  StatusTicketIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AktivasiRoute: AktivasiRouteWithChildren,
  CekStatusRoute: CekStatusRoute,
  KodeAksesRoute: KodeAksesRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRouteWithChildren,
  PcRoute: PcRouteWithChildren,
  PwRoute: PwRouteWithChildren,
  ReviewRoute: ReviewRouteWithChildren,
  StatusTicketIdRoute: StatusTicketIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
