/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PwRouteImport } from './routes/pw'
import { Route as PcRouteImport } from './routes/pc'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KodeAksesRouteImport } from './routes/kode-akses'
import { Route as CekStatusRouteImport } from './routes/cek-status'
import { Route as AktivasiRouteImport } from './routes/aktivasi'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as PwIndexRouteImport } from './routes/pw.index'
import { Route as PcIndexRouteImport } from './routes/pc.index'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StatusTicketIdRouteImport } from './routes/status.$ticketId'
import { Route as ReviewPeruriRouteImport } from './routes/review.peruri'
import { Route as ReviewNotificationsRouteImport } from './routes/review.notifications'
import { Route as ReviewInboxRouteImport } from './routes/review.inbox'
import { Route as ReviewAuditLogRouteImport } from './routes/review.audit-log'
import { Route as PwNotificationsRouteImport } from './routes/pw.notifications'
import { Route as PwDaftarkanRouteImport } from './routes/pw.daftarkan'
import { Route as PcNotificationsRouteImport } from './routes/pc.notifications'
import { Route as PcDaftarkanRouteImport } from './routes/pc.daftarkan'
import { Route as OpsUsersRouteImport } from './routes/ops.users'
import { Route as OpsRolesRouteImport } from './routes/ops.roles'
import { Route as OpsRepositoryRouteImport } from './routes/ops.repository'
import { Route as AktivasiAccessCodeRouteImport } from './routes/aktivasi.$accessCode'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminAccessCodesRouteImport } from './routes/admin.access-codes'
import { Route as PwStatusPengajuanIndexRouteImport } from './routes/pw.status-pengajuan.index'
import { Route as PcStatusPengajuanIndexRouteImport } from './routes/pc.status-pengajuan.index'
import { Route as OpsActivationIndexRouteImport } from './routes/ops.activation.index'
import { Route as StatusTicketIdRevisiRouteImport } from './routes/status.$ticketId.revisi'
import { Route as ReviewInboxTicketIdRouteImport } from './routes/review.inbox.$ticketId'
import { Route as PwStatusPengajuanTicketIdRouteImport } from './routes/pw.status-pengajuan.$ticketId'
import { Route as PcStatusPengajuanTicketIdRouteImport } from './routes/pc.status-pengajuan.$ticketId'
import { Route as OpsPersuratanStamperRouteImport } from './routes/ops.persuratan.stamper'
import { Route as OpsPersuratanPengajuanUbahEmailRouteImport } from './routes/ops.persuratan.pengajuan-ubah-email'
import { Route as OpsPersuratanKopSuratRouteImport } from './routes/ops.persuratan.kop-surat'
import { Route as OpsPersuratanCekOrderIdRouteImport } from './routes/ops.persuratan.cek-order-id'
import { Route as OpsActivationSubmissionsRouteImport } from './routes/ops.activation.submissions'
import { Route as OpsActivationPeruriExportRouteImport } from './routes/ops.activation.peruri-export'
import { Route as OpsActivationNotificationsRouteImport } from './routes/ops.activation.notifications'
import { Route as OpsActivationAuditLogRouteImport } from './routes/ops.activation.audit-log'
import { Route as OpsActivationAccessCodesRouteImport } from './routes/ops.activation.access-codes'
import { Route as AktivasiSuksesTicketIdRouteImport } from './routes/aktivasi.sukses.$ticketId'
import { Route as PwStatusPengajuanTicketIdRevisiRouteImport } from './routes/pw.status-pengajuan.$ticketId.revisi'
import { Route as PcStatusPengajuanTicketIdRevisiRouteImport } from './routes/pc.status-pengajuan.$ticketId.revisi'
import { Route as OpsActivationSubmissionsTicketIdRouteImport } from './routes/ops.activation.submissions_.$ticketId'
import { Route as OpsActivationAccessCodesCodeIdRouteImport } from './routes/ops.activation.access-codes_.$codeId'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PwRoute = PwRouteImport.update({
  id: '/pw',
  path: '/pw',
  getParentRoute: () => rootRouteImport,
} as any)
const PcRoute = PcRouteImport.update({
  id: '/pc',
  path: '/pc',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KodeAksesRoute = KodeAksesRouteImport.update({
  id: '/kode-akses',
  path: '/kode-akses',
  getParentRoute: () => rootRouteImport,
} as any)
const CekStatusRoute = CekStatusRouteImport.update({
  id: '/cek-status',
  path: '/cek-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AktivasiRoute = AktivasiRouteImport.update({
  id: '/aktivasi',
  path: '/aktivasi',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewRoute,
} as any)
const PwIndexRoute = PwIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PwRoute,
} as any)
const PcIndexRoute = PcIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PcRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StatusTicketIdRoute = StatusTicketIdRouteImport.update({
  id: '/status/$ticketId',
  path: '/status/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewPeruriRoute = ReviewPeruriRouteImport.update({
  id: '/peruri',
  path: '/peruri',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewNotificationsRoute = ReviewNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewInboxRoute = ReviewInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewAuditLogRoute = ReviewAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => ReviewRoute,
} as any)
const PwNotificationsRoute = PwNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PwRoute,
} as any)
const PwDaftarkanRoute = PwDaftarkanRouteImport.update({
  id: '/daftarkan',
  path: '/daftarkan',
  getParentRoute: () => PwRoute,
} as any)
const PcNotificationsRoute = PcNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PcRoute,
} as any)
const PcDaftarkanRoute = PcDaftarkanRouteImport.update({
  id: '/daftarkan',
  path: '/daftarkan',
  getParentRoute: () => PcRoute,
} as any)
const OpsUsersRoute = OpsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => OpsRoute,
} as any)
const OpsRolesRoute = OpsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => OpsRoute,
} as any)
const OpsRepositoryRoute = OpsRepositoryRouteImport.update({
  id: '/repository',
  path: '/repository',
  getParentRoute: () => OpsRoute,
} as any)
const AktivasiAccessCodeRoute = AktivasiAccessCodeRouteImport.update({
  id: '/$accessCode',
  path: '/$accessCode',
  getParentRoute: () => AktivasiRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessCodesRoute = AdminAccessCodesRouteImport.update({
  id: '/access-codes',
  path: '/access-codes',
  getParentRoute: () => AdminRoute,
} as any)
const PwStatusPengajuanIndexRoute = PwStatusPengajuanIndexRouteImport.update({
  id: '/status-pengajuan/',
  path: '/status-pengajuan/',
  getParentRoute: () => PwRoute,
} as any)
const PcStatusPengajuanIndexRoute = PcStatusPengajuanIndexRouteImport.update({
  id: '/status-pengajuan/',
  path: '/status-pengajuan/',
  getParentRoute: () => PcRoute,
} as any)
const OpsActivationIndexRoute = OpsActivationIndexRouteImport.update({
  id: '/activation/',
  path: '/activation/',
  getParentRoute: () => OpsRoute,
} as any)
const StatusTicketIdRevisiRoute = StatusTicketIdRevisiRouteImport.update({
  id: '/revisi',
  path: '/revisi',
  getParentRoute: () => StatusTicketIdRoute,
} as any)
const ReviewInboxTicketIdRoute = ReviewInboxTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => ReviewInboxRoute,
} as any)
const PwStatusPengajuanTicketIdRoute =
  PwStatusPengajuanTicketIdRouteImport.update({
    id: '/status-pengajuan/$ticketId',
    path: '/status-pengajuan/$ticketId',
    getParentRoute: () => PwRoute,
  } as any)
const PcStatusPengajuanTicketIdRoute =
  PcStatusPengajuanTicketIdRouteImport.update({
    id: '/status-pengajuan/$ticketId',
    path: '/status-pengajuan/$ticketId',
    getParentRoute: () => PcRoute,
  } as any)
const OpsPersuratanStamperRoute = OpsPersuratanStamperRouteImport.update({
  id: '/persuratan/stamper',
  path: '/persuratan/stamper',
  getParentRoute: () => OpsRoute,
} as any)
const OpsPersuratanPengajuanUbahEmailRoute =
  OpsPersuratanPengajuanUbahEmailRouteImport.update({
    id: '/persuratan/pengajuan-ubah-email',
    path: '/persuratan/pengajuan-ubah-email',
    getParentRoute: () => OpsRoute,
  } as any)
const OpsPersuratanKopSuratRoute = OpsPersuratanKopSuratRouteImport.update({
  id: '/persuratan/kop-surat',
  path: '/persuratan/kop-surat',
  getParentRoute: () => OpsRoute,
} as any)
const OpsPersuratanCekOrderIdRoute = OpsPersuratanCekOrderIdRouteImport.update({
  id: '/persuratan/cek-order-id',
  path: '/persuratan/cek-order-id',
  getParentRoute: () => OpsRoute,
} as any)
const OpsActivationSubmissionsRoute =
  OpsActivationSubmissionsRouteImport.update({
    id: '/activation/submissions',
    path: '/activation/submissions',
    getParentRoute: () => OpsRoute,
  } as any)
const OpsActivationPeruriExportRoute =
  OpsActivationPeruriExportRouteImport.update({
    id: '/activation/peruri-export',
    path: '/activation/peruri-export',
    getParentRoute: () => OpsRoute,
  } as any)
const OpsActivationNotificationsRoute =
  OpsActivationNotificationsRouteImport.update({
    id: '/activation/notifications',
    path: '/activation/notifications',
    getParentRoute: () => OpsRoute,
  } as any)
const OpsActivationAuditLogRoute = OpsActivationAuditLogRouteImport.update({
  id: '/activation/audit-log',
  path: '/activation/audit-log',
  getParentRoute: () => OpsRoute,
} as any)
const OpsActivationAccessCodesRoute =
  OpsActivationAccessCodesRouteImport.update({
    id: '/activation/access-codes',
    path: '/activation/access-codes',
    getParentRoute: () => OpsRoute,
  } as any)
const AktivasiSuksesTicketIdRoute = AktivasiSuksesTicketIdRouteImport.update({
  id: '/sukses/$ticketId',
  path: '/sukses/$ticketId',
  getParentRoute: () => AktivasiRoute,
} as any)
const PwStatusPengajuanTicketIdRevisiRoute =
  PwStatusPengajuanTicketIdRevisiRouteImport.update({
    id: '/revisi',
    path: '/revisi',
    getParentRoute: () => PwStatusPengajuanTicketIdRoute,
  } as any)
const PcStatusPengajuanTicketIdRevisiRoute =
  PcStatusPengajuanTicketIdRevisiRouteImport.update({
    id: '/revisi',
    path: '/revisi',
    getParentRoute: () => PcStatusPengajuanTicketIdRoute,
  } as any)
const OpsActivationSubmissionsTicketIdRoute =
  OpsActivationSubmissionsTicketIdRouteImport.update({
    id: '/activation/submissions_/$ticketId',
    path: '/activation/submissions/$ticketId',
    getParentRoute: () => OpsRoute,
  } as any)
const OpsActivationAccessCodesCodeIdRoute =
  OpsActivationAccessCodesCodeIdRouteImport.update({
    id: '/activation/access-codes_/$codeId',
    path: '/activation/access-codes/$codeId',
    getParentRoute: () => OpsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aktivasi': typeof AktivasiRouteWithChildren
  '/cek-status': typeof CekStatusRoute
  '/kode-akses': typeof KodeAksesRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/pc': typeof PcRouteWithChildren
  '/pw': typeof PwRouteWithChildren
  '/review': typeof ReviewRouteWithChildren
  '/admin/access-codes': typeof AdminAccessCodesRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/aktivasi/$accessCode': typeof AktivasiAccessCodeRoute
  '/ops/repository': typeof OpsRepositoryRoute
  '/ops/roles': typeof OpsRolesRoute
  '/ops/users': typeof OpsUsersRoute
  '/pc/daftarkan': typeof PcDaftarkanRoute
  '/pc/notifications': typeof PcNotificationsRoute
  '/pw/daftarkan': typeof PwDaftarkanRoute
  '/pw/notifications': typeof PwNotificationsRoute
  '/review/audit-log': typeof ReviewAuditLogRoute
  '/review/inbox': typeof ReviewInboxRouteWithChildren
  '/review/notifications': typeof ReviewNotificationsRoute
  '/review/peruri': typeof ReviewPeruriRoute
  '/status/$ticketId': typeof StatusTicketIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/pc/': typeof PcIndexRoute
  '/pw/': typeof PwIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/aktivasi/sukses/$ticketId': typeof AktivasiSuksesTicketIdRoute
  '/ops/activation/access-codes': typeof OpsActivationAccessCodesRoute
  '/ops/activation/audit-log': typeof OpsActivationAuditLogRoute
  '/ops/activation/notifications': typeof OpsActivationNotificationsRoute
  '/ops/activation/peruri-export': typeof OpsActivationPeruriExportRoute
  '/ops/activation/submissions': typeof OpsActivationSubmissionsRoute
  '/ops/persuratan/cek-order-id': typeof OpsPersuratanCekOrderIdRoute
  '/ops/persuratan/kop-surat': typeof OpsPersuratanKopSuratRoute
  '/ops/persuratan/pengajuan-ubah-email': typeof OpsPersuratanPengajuanUbahEmailRoute
  '/ops/persuratan/stamper': typeof OpsPersuratanStamperRoute
  '/pc/status-pengajuan/$ticketId': typeof PcStatusPengajuanTicketIdRouteWithChildren
  '/pw/status-pengajuan/$ticketId': typeof PwStatusPengajuanTicketIdRouteWithChildren
  '/review/inbox/$ticketId': typeof ReviewInboxTicketIdRoute
  '/status/$ticketId/revisi': typeof StatusTicketIdRevisiRoute
  '/ops/activation/': typeof OpsActivationIndexRoute
  '/pc/status-pengajuan/': typeof PcStatusPengajuanIndexRoute
  '/pw/status-pengajuan/': typeof PwStatusPengajuanIndexRoute
  '/ops/activation/access-codes/$codeId': typeof OpsActivationAccessCodesCodeIdRoute
  '/ops/activation/submissions/$ticketId': typeof OpsActivationSubmissionsTicketIdRoute
  '/pc/status-pengajuan/$ticketId/revisi': typeof PcStatusPengajuanTicketIdRevisiRoute
  '/pw/status-pengajuan/$ticketId/revisi': typeof PwStatusPengajuanTicketIdRevisiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aktivasi': typeof AktivasiRouteWithChildren
  '/cek-status': typeof CekStatusRoute
  '/kode-akses': typeof KodeAksesRoute
  '/login': typeof LoginRoute
  '/admin/access-codes': typeof AdminAccessCodesRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/aktivasi/$accessCode': typeof AktivasiAccessCodeRoute
  '/ops/repository': typeof OpsRepositoryRoute
  '/ops/roles': typeof OpsRolesRoute
  '/ops/users': typeof OpsUsersRoute
  '/pc/daftarkan': typeof PcDaftarkanRoute
  '/pc/notifications': typeof PcNotificationsRoute
  '/pw/daftarkan': typeof PwDaftarkanRoute
  '/pw/notifications': typeof PwNotificationsRoute
  '/review/audit-log': typeof ReviewAuditLogRoute
  '/review/inbox': typeof ReviewInboxRouteWithChildren
  '/review/notifications': typeof ReviewNotificationsRoute
  '/review/peruri': typeof ReviewPeruriRoute
  '/status/$ticketId': typeof StatusTicketIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/ops': typeof OpsIndexRoute
  '/pc': typeof PcIndexRoute
  '/pw': typeof PwIndexRoute
  '/review': typeof ReviewIndexRoute
  '/aktivasi/sukses/$ticketId': typeof AktivasiSuksesTicketIdRoute
  '/ops/activation/access-codes': typeof OpsActivationAccessCodesRoute
  '/ops/activation/audit-log': typeof OpsActivationAuditLogRoute
  '/ops/activation/notifications': typeof OpsActivationNotificationsRoute
  '/ops/activation/peruri-export': typeof OpsActivationPeruriExportRoute
  '/ops/activation/submissions': typeof OpsActivationSubmissionsRoute
  '/ops/persuratan/cek-order-id': typeof OpsPersuratanCekOrderIdRoute
  '/ops/persuratan/kop-surat': typeof OpsPersuratanKopSuratRoute
  '/ops/persuratan/pengajuan-ubah-email': typeof OpsPersuratanPengajuanUbahEmailRoute
  '/ops/persuratan/stamper': typeof OpsPersuratanStamperRoute
  '/pc/status-pengajuan/$ticketId': typeof PcStatusPengajuanTicketIdRouteWithChildren
  '/pw/status-pengajuan/$ticketId': typeof PwStatusPengajuanTicketIdRouteWithChildren
  '/review/inbox/$ticketId': typeof ReviewInboxTicketIdRoute
  '/status/$ticketId/revisi': typeof StatusTicketIdRevisiRoute
  '/ops/activation': typeof OpsActivationIndexRoute
  '/pc/status-pengajuan': typeof PcStatusPengajuanIndexRoute
  '/pw/status-pengajuan': typeof PwStatusPengajuanIndexRoute
  '/ops/activation/access-codes/$codeId': typeof OpsActivationAccessCodesCodeIdRoute
  '/ops/activation/submissions/$ticketId': typeof OpsActivationSubmissionsTicketIdRoute
  '/pc/status-pengajuan/$ticketId/revisi': typeof PcStatusPengajuanTicketIdRevisiRoute
  '/pw/status-pengajuan/$ticketId/revisi': typeof PwStatusPengajuanTicketIdRevisiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aktivasi': typeof AktivasiRouteWithChildren
  '/cek-status': typeof CekStatusRoute
  '/kode-akses': typeof KodeAksesRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/pc': typeof PcRouteWithChildren
  '/pw': typeof PwRouteWithChildren
  '/review': typeof ReviewRouteWithChildren
  '/admin/access-codes': typeof AdminAccessCodesRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/aktivasi/$accessCode': typeof AktivasiAccessCodeRoute
  '/ops/repository': typeof OpsRepositoryRoute
  '/ops/roles': typeof OpsRolesRoute
  '/ops/users': typeof OpsUsersRoute
  '/pc/daftarkan': typeof PcDaftarkanRoute
  '/pc/notifications': typeof PcNotificationsRoute
  '/pw/daftarkan': typeof PwDaftarkanRoute
  '/pw/notifications': typeof PwNotificationsRoute
  '/review/audit-log': typeof ReviewAuditLogRoute
  '/review/inbox': typeof ReviewInboxRouteWithChildren
  '/review/notifications': typeof ReviewNotificationsRoute
  '/review/peruri': typeof ReviewPeruriRoute
  '/status/$ticketId': typeof StatusTicketIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/pc/': typeof PcIndexRoute
  '/pw/': typeof PwIndexRoute
  '/review/': typeof ReviewIndexRoute
  '/aktivasi/sukses/$ticketId': typeof AktivasiSuksesTicketIdRoute
  '/ops/activation/access-codes': typeof OpsActivationAccessCodesRoute
  '/ops/activation/audit-log': typeof OpsActivationAuditLogRoute
  '/ops/activation/notifications': typeof OpsActivationNotificationsRoute
  '/ops/activation/peruri-export': typeof OpsActivationPeruriExportRoute
  '/ops/activation/submissions': typeof OpsActivationSubmissionsRoute
  '/ops/persuratan/cek-order-id': typeof OpsPersuratanCekOrderIdRoute
  '/ops/persuratan/kop-surat': typeof OpsPersuratanKopSuratRoute
  '/ops/persuratan/pengajuan-ubah-email': typeof OpsPersuratanPengajuanUbahEmailRoute
  '/ops/persuratan/stamper': typeof OpsPersuratanStamperRoute
  '/pc/status-pengajuan/$ticketId': typeof PcStatusPengajuanTicketIdRouteWithChildren
  '/pw/status-pengajuan/$ticketId': typeof PwStatusPengajuanTicketIdRouteWithChildren
  '/review/inbox/$ticketId': typeof ReviewInboxTicketIdRoute
  '/status/$ticketId/revisi': typeof StatusTicketIdRevisiRoute
  '/ops/activation/': typeof OpsActivationIndexRoute
  '/pc/status-pengajuan/': typeof PcStatusPengajuanIndexRoute
  '/pw/status-pengajuan/': typeof PwStatusPengajuanIndexRoute
  '/ops/activation/access-codes_/$codeId': typeof OpsActivationAccessCodesCodeIdRoute
  '/ops/activation/submissions_/$ticketId': typeof OpsActivationSubmissionsTicketIdRoute
  '/pc/status-pengajuan/$ticketId/revisi': typeof PcStatusPengajuanTicketIdRevisiRoute
  '/pw/status-pengajuan/$ticketId/revisi': typeof PwStatusPengajuanTicketIdRevisiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aktivasi'
    | '/cek-status'
    | '/kode-akses'
    | '/login'
    | '/ops'
    | '/pc'
    | '/pw'
    | '/review'
    | '/admin/access-codes'
    | '/admin/audit-log'
    | '/admin/settings'
    | '/aktivasi/$accessCode'
    | '/ops/repository'
    | '/ops/roles'
    | '/ops/users'
    | '/pc/daftarkan'
    | '/pc/notifications'
    | '/pw/daftarkan'
    | '/pw/notifications'
    | '/review/audit-log'
    | '/review/inbox'
    | '/review/notifications'
    | '/review/peruri'
    | '/status/$ticketId'
    | '/admin/'
    | '/ops/'
    | '/pc/'
    | '/pw/'
    | '/review/'
    | '/aktivasi/sukses/$ticketId'
    | '/ops/activation/access-codes'
    | '/ops/activation/audit-log'
    | '/ops/activation/notifications'
    | '/ops/activation/peruri-export'
    | '/ops/activation/submissions'
    | '/ops/persuratan/cek-order-id'
    | '/ops/persuratan/kop-surat'
    | '/ops/persuratan/pengajuan-ubah-email'
    | '/ops/persuratan/stamper'
    | '/pc/status-pengajuan/$ticketId'
    | '/pw/status-pengajuan/$ticketId'
    | '/review/inbox/$ticketId'
    | '/status/$ticketId/revisi'
    | '/ops/activation/'
    | '/pc/status-pengajuan/'
    | '/pw/status-pengajuan/'
    | '/ops/activation/access-codes/$codeId'
    | '/ops/activation/submissions/$ticketId'
    | '/pc/status-pengajuan/$ticketId/revisi'
    | '/pw/status-pengajuan/$ticketId/revisi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aktivasi'
    | '/cek-status'
    | '/kode-akses'
    | '/login'
    | '/admin/access-codes'
    | '/admin/audit-log'
    | '/admin/settings'
    | '/aktivasi/$accessCode'
    | '/ops/repository'
    | '/ops/roles'
    | '/ops/users'
    | '/pc/daftarkan'
    | '/pc/notifications'
    | '/pw/daftarkan'
    | '/pw/notifications'
    | '/review/audit-log'
    | '/review/inbox'
    | '/review/notifications'
    | '/review/peruri'
    | '/status/$ticketId'
    | '/admin'
    | '/ops'
    | '/pc'
    | '/pw'
    | '/review'
    | '/aktivasi/sukses/$ticketId'
    | '/ops/activation/access-codes'
    | '/ops/activation/audit-log'
    | '/ops/activation/notifications'
    | '/ops/activation/peruri-export'
    | '/ops/activation/submissions'
    | '/ops/persuratan/cek-order-id'
    | '/ops/persuratan/kop-surat'
    | '/ops/persuratan/pengajuan-ubah-email'
    | '/ops/persuratan/stamper'
    | '/pc/status-pengajuan/$ticketId'
    | '/pw/status-pengajuan/$ticketId'
    | '/review/inbox/$ticketId'
    | '/status/$ticketId/revisi'
    | '/ops/activation'
    | '/pc/status-pengajuan'
    | '/pw/status-pengajuan'
    | '/ops/activation/access-codes/$codeId'
    | '/ops/activation/submissions/$ticketId'
    | '/pc/status-pengajuan/$ticketId/revisi'
    | '/pw/status-pengajuan/$ticketId/revisi'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aktivasi'
    | '/cek-status'
    | '/kode-akses'
    | '/login'
    | '/ops'
    | '/pc'
    | '/pw'
    | '/review'
    | '/admin/access-codes'
    | '/admin/audit-log'
    | '/admin/settings'
    | '/aktivasi/$accessCode'
    | '/ops/repository'
    | '/ops/roles'
    | '/ops/users'
    | '/pc/daftarkan'
    | '/pc/notifications'
    | '/pw/daftarkan'
    | '/pw/notifications'
    | '/review/audit-log'
    | '/review/inbox'
    | '/review/notifications'
    | '/review/peruri'
    | '/status/$ticketId'
    | '/admin/'
    | '/ops/'
    | '/pc/'
    | '/pw/'
    | '/review/'
    | '/aktivasi/sukses/$ticketId'
    | '/ops/activation/access-codes'
    | '/ops/activation/audit-log'
    | '/ops/activation/notifications'
    | '/ops/activation/peruri-export'
    | '/ops/activation/submissions'
    | '/ops/persuratan/cek-order-id'
    | '/ops/persuratan/kop-surat'
    | '/ops/persuratan/pengajuan-ubah-email'
    | '/ops/persuratan/stamper'
    | '/pc/status-pengajuan/$ticketId'
    | '/pw/status-pengajuan/$ticketId'
    | '/review/inbox/$ticketId'
    | '/status/$ticketId/revisi'
    | '/ops/activation/'
    | '/pc/status-pengajuan/'
    | '/pw/status-pengajuan/'
    | '/ops/activation/access-codes_/$codeId'
    | '/ops/activation/submissions_/$ticketId'
    | '/pc/status-pengajuan/$ticketId/revisi'
    | '/pw/status-pengajuan/$ticketId/revisi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AktivasiRoute: typeof AktivasiRouteWithChildren
  CekStatusRoute: typeof CekStatusRoute
  KodeAksesRoute: typeof KodeAksesRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRouteWithChildren
  PcRoute: typeof PcRouteWithChildren
  PwRoute: typeof PwRouteWithChildren
  ReviewRoute: typeof ReviewRouteWithChildren
  StatusTicketIdRoute: typeof StatusTicketIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pw': {
      id: '/pw'
      path: '/pw'
      fullPath: '/pw'
      preLoaderRoute: typeof PwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pc': {
      id: '/pc'
      path: '/pc'
      fullPath: '/pc'
      preLoaderRoute: typeof PcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kode-akses': {
      id: '/kode-akses'
      path: '/kode-akses'
      fullPath: '/kode-akses'
      preLoaderRoute: typeof KodeAksesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cek-status': {
      id: '/cek-status'
      path: '/cek-status'
      fullPath: '/cek-status'
      preLoaderRoute: typeof CekStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivasi': {
      id: '/aktivasi'
      path: '/aktivasi'
      fullPath: '/aktivasi'
      preLoaderRoute: typeof AktivasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/pw/': {
      id: '/pw/'
      path: '/'
      fullPath: '/pw/'
      preLoaderRoute: typeof PwIndexRouteImport
      parentRoute: typeof PwRoute
    }
    '/pc/': {
      id: '/pc/'
      path: '/'
      fullPath: '/pc/'
      preLoaderRoute: typeof PcIndexRouteImport
      parentRoute: typeof PcRoute
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/status/$ticketId': {
      id: '/status/$ticketId'
      path: '/status/$ticketId'
      fullPath: '/status/$ticketId'
      preLoaderRoute: typeof StatusTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/peruri': {
      id: '/review/peruri'
      path: '/peruri'
      fullPath: '/review/peruri'
      preLoaderRoute: typeof ReviewPeruriRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/notifications': {
      id: '/review/notifications'
      path: '/notifications'
      fullPath: '/review/notifications'
      preLoaderRoute: typeof ReviewNotificationsRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/inbox': {
      id: '/review/inbox'
      path: '/inbox'
      fullPath: '/review/inbox'
      preLoaderRoute: typeof ReviewInboxRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/audit-log': {
      id: '/review/audit-log'
      path: '/audit-log'
      fullPath: '/review/audit-log'
      preLoaderRoute: typeof ReviewAuditLogRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/pw/notifications': {
      id: '/pw/notifications'
      path: '/notifications'
      fullPath: '/pw/notifications'
      preLoaderRoute: typeof PwNotificationsRouteImport
      parentRoute: typeof PwRoute
    }
    '/pw/daftarkan': {
      id: '/pw/daftarkan'
      path: '/daftarkan'
      fullPath: '/pw/daftarkan'
      preLoaderRoute: typeof PwDaftarkanRouteImport
      parentRoute: typeof PwRoute
    }
    '/pc/notifications': {
      id: '/pc/notifications'
      path: '/notifications'
      fullPath: '/pc/notifications'
      preLoaderRoute: typeof PcNotificationsRouteImport
      parentRoute: typeof PcRoute
    }
    '/pc/daftarkan': {
      id: '/pc/daftarkan'
      path: '/daftarkan'
      fullPath: '/pc/daftarkan'
      preLoaderRoute: typeof PcDaftarkanRouteImport
      parentRoute: typeof PcRoute
    }
    '/ops/users': {
      id: '/ops/users'
      path: '/users'
      fullPath: '/ops/users'
      preLoaderRoute: typeof OpsUsersRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/roles': {
      id: '/ops/roles'
      path: '/roles'
      fullPath: '/ops/roles'
      preLoaderRoute: typeof OpsRolesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/repository': {
      id: '/ops/repository'
      path: '/repository'
      fullPath: '/ops/repository'
      preLoaderRoute: typeof OpsRepositoryRouteImport
      parentRoute: typeof OpsRoute
    }
    '/aktivasi/$accessCode': {
      id: '/aktivasi/$accessCode'
      path: '/$accessCode'
      fullPath: '/aktivasi/$accessCode'
      preLoaderRoute: typeof AktivasiAccessCodeRouteImport
      parentRoute: typeof AktivasiRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access-codes': {
      id: '/admin/access-codes'
      path: '/access-codes'
      fullPath: '/admin/access-codes'
      preLoaderRoute: typeof AdminAccessCodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pw/status-pengajuan/': {
      id: '/pw/status-pengajuan/'
      path: '/status-pengajuan'
      fullPath: '/pw/status-pengajuan/'
      preLoaderRoute: typeof PwStatusPengajuanIndexRouteImport
      parentRoute: typeof PwRoute
    }
    '/pc/status-pengajuan/': {
      id: '/pc/status-pengajuan/'
      path: '/status-pengajuan'
      fullPath: '/pc/status-pengajuan/'
      preLoaderRoute: typeof PcStatusPengajuanIndexRouteImport
      parentRoute: typeof PcRoute
    }
    '/ops/activation/': {
      id: '/ops/activation/'
      path: '/activation'
      fullPath: '/ops/activation/'
      preLoaderRoute: typeof OpsActivationIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/status/$ticketId/revisi': {
      id: '/status/$ticketId/revisi'
      path: '/revisi'
      fullPath: '/status/$ticketId/revisi'
      preLoaderRoute: typeof StatusTicketIdRevisiRouteImport
      parentRoute: typeof StatusTicketIdRoute
    }
    '/review/inbox/$ticketId': {
      id: '/review/inbox/$ticketId'
      path: '/$ticketId'
      fullPath: '/review/inbox/$ticketId'
      preLoaderRoute: typeof ReviewInboxTicketIdRouteImport
      parentRoute: typeof ReviewInboxRoute
    }
    '/pw/status-pengajuan/$ticketId': {
      id: '/pw/status-pengajuan/$ticketId'
      path: '/status-pengajuan/$ticketId'
      fullPath: '/pw/status-pengajuan/$ticketId'
      preLoaderRoute: typeof PwStatusPengajuanTicketIdRouteImport
      parentRoute: typeof PwRoute
    }
    '/pc/status-pengajuan/$ticketId': {
      id: '/pc/status-pengajuan/$ticketId'
      path: '/status-pengajuan/$ticketId'
      fullPath: '/pc/status-pengajuan/$ticketId'
      preLoaderRoute: typeof PcStatusPengajuanTicketIdRouteImport
      parentRoute: typeof PcRoute
    }
    '/ops/persuratan/stamper': {
      id: '/ops/persuratan/stamper'
      path: '/persuratan/stamper'
      fullPath: '/ops/persuratan/stamper'
      preLoaderRoute: typeof OpsPersuratanStamperRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/persuratan/pengajuan-ubah-email': {
      id: '/ops/persuratan/pengajuan-ubah-email'
      path: '/persuratan/pengajuan-ubah-email'
      fullPath: '/ops/persuratan/pengajuan-ubah-email'
      preLoaderRoute: typeof OpsPersuratanPengajuanUbahEmailRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/persuratan/kop-surat': {
      id: '/ops/persuratan/kop-surat'
      path: '/persuratan/kop-surat'
      fullPath: '/ops/persuratan/kop-surat'
      preLoaderRoute: typeof OpsPersuratanKopSuratRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/persuratan/cek-order-id': {
      id: '/ops/persuratan/cek-order-id'
      path: '/persuratan/cek-order-id'
      fullPath: '/ops/persuratan/cek-order-id'
      preLoaderRoute: typeof OpsPersuratanCekOrderIdRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/activation/submissions': {
      id: '/ops/activation/submissions'
      path: '/activation/submissions'
      fullPath: '/ops/activation/submissions'
      preLoaderRoute: typeof OpsActivationSubmissionsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/activation/peruri-export': {
      id: '/ops/activation/peruri-export'
      path: '/activation/peruri-export'
      fullPath: '/ops/activation/peruri-export'
      preLoaderRoute: typeof OpsActivationPeruriExportRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/activation/notifications': {
      id: '/ops/activation/notifications'
      path: '/activation/notifications'
      fullPath: '/ops/activation/notifications'
      preLoaderRoute: typeof OpsActivationNotificationsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/activation/audit-log': {
      id: '/ops/activation/audit-log'
      path: '/activation/audit-log'
      fullPath: '/ops/activation/audit-log'
      preLoaderRoute: typeof OpsActivationAuditLogRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/activation/access-codes': {
      id: '/ops/activation/access-codes'
      path: '/activation/access-codes'
      fullPath: '/ops/activation/access-codes'
      preLoaderRoute: typeof OpsActivationAccessCodesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/aktivasi/sukses/$ticketId': {
      id: '/aktivasi/sukses/$ticketId'
      path: '/sukses/$ticketId'
      fullPath: '/aktivasi/sukses/$ticketId'
      preLoaderRoute: typeof AktivasiSuksesTicketIdRouteImport
      parentRoute: typeof AktivasiRoute
    }
    '/pw/status-pengajuan/$ticketId/revisi': {
      id: '/pw/status-pengajuan/$ticketId/revisi'
      path: '/revisi'
      fullPath: '/pw/status-pengajuan/$ticketId/revisi'
      preLoaderRoute: typeof PwStatusPengajuanTicketIdRevisiRouteImport
      parentRoute: typeof PwStatusPengajuanTicketIdRoute
    }
    '/pc/status-pengajuan/$ticketId/revisi': {
      id: '/pc/status-pengajuan/$ticketId/revisi'
      path: '/revisi'
      fullPath: '/pc/status-pengajuan/$ticketId/revisi'
      preLoaderRoute: typeof PcStatusPengajuanTicketIdRevisiRouteImport
      parentRoute: typeof PcStatusPengajuanTicketIdRoute
    }
    '/ops/activation/submissions_/$ticketId': {
      id: '/ops/activation/submissions_/$ticketId'
      path: '/activation/submissions/$ticketId'
      fullPath: '/ops/activation/submissions/$ticketId'
      preLoaderRoute: typeof OpsActivationSubmissionsTicketIdRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/activation/access-codes_/$codeId': {
      id: '/ops/activation/access-codes_/$codeId'
      path: '/activation/access-codes/$codeId'
      fullPath: '/ops/activation/access-codes/$codeId'
      preLoaderRoute: typeof OpsActivationAccessCodesCodeIdRouteImport
      parentRoute: typeof OpsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccessCodesRoute: typeof AdminAccessCodesRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessCodesRoute: AdminAccessCodesRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AktivasiRouteChildren {
  AktivasiAccessCodeRoute: typeof AktivasiAccessCodeRoute
  AktivasiSuksesTicketIdRoute: typeof AktivasiSuksesTicketIdRoute
}

const AktivasiRouteChildren: AktivasiRouteChildren = {
  AktivasiAccessCodeRoute: AktivasiAccessCodeRoute,
  AktivasiSuksesTicketIdRoute: AktivasiSuksesTicketIdRoute,
}

const AktivasiRouteWithChildren = AktivasiRoute._addFileChildren(
  AktivasiRouteChildren,
)

interface OpsRouteChildren {
  OpsRepositoryRoute: typeof OpsRepositoryRoute
  OpsRolesRoute: typeof OpsRolesRoute
  OpsUsersRoute: typeof OpsUsersRoute
  OpsIndexRoute: typeof OpsIndexRoute
  OpsActivationAccessCodesRoute: typeof OpsActivationAccessCodesRoute
  OpsActivationAuditLogRoute: typeof OpsActivationAuditLogRoute
  OpsActivationNotificationsRoute: typeof OpsActivationNotificationsRoute
  OpsActivationPeruriExportRoute: typeof OpsActivationPeruriExportRoute
  OpsActivationSubmissionsRoute: typeof OpsActivationSubmissionsRoute
  OpsPersuratanCekOrderIdRoute: typeof OpsPersuratanCekOrderIdRoute
  OpsPersuratanKopSuratRoute: typeof OpsPersuratanKopSuratRoute
  OpsPersuratanPengajuanUbahEmailRoute: typeof OpsPersuratanPengajuanUbahEmailRoute
  OpsPersuratanStamperRoute: typeof OpsPersuratanStamperRoute
  OpsActivationIndexRoute: typeof OpsActivationIndexRoute
  OpsActivationAccessCodesCodeIdRoute: typeof OpsActivationAccessCodesCodeIdRoute
  OpsActivationSubmissionsTicketIdRoute: typeof OpsActivationSubmissionsTicketIdRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsRepositoryRoute: OpsRepositoryRoute,
  OpsRolesRoute: OpsRolesRoute,
  OpsUsersRoute: OpsUsersRoute,
  OpsIndexRoute: OpsIndexRoute,
  OpsActivationAccessCodesRoute: OpsActivationAccessCodesRoute,
  OpsActivationAuditLogRoute: OpsActivationAuditLogRoute,
  OpsActivationNotificationsRoute: OpsActivationNotificationsRoute,
  OpsActivationPeruriExportRoute: OpsActivationPeruriExportRoute,
  OpsActivationSubmissionsRoute: OpsActivationSubmissionsRoute,
  OpsPersuratanCekOrderIdRoute: OpsPersuratanCekOrderIdRoute,
  OpsPersuratanKopSuratRoute: OpsPersuratanKopSuratRoute,
  OpsPersuratanPengajuanUbahEmailRoute: OpsPersuratanPengajuanUbahEmailRoute,
  OpsPersuratanStamperRoute: OpsPersuratanStamperRoute,
  OpsActivationIndexRoute: OpsActivationIndexRoute,
  OpsActivationAccessCodesCodeIdRoute: OpsActivationAccessCodesCodeIdRoute,
  OpsActivationSubmissionsTicketIdRoute: OpsActivationSubmissionsTicketIdRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

interface PcStatusPengajuanTicketIdRouteChildren {
  PcStatusPengajuanTicketIdRevisiRoute: typeof PcStatusPengajuanTicketIdRevisiRoute
}

const PcStatusPengajuanTicketIdRouteChildren: PcStatusPengajuanTicketIdRouteChildren =
  {
    PcStatusPengajuanTicketIdRevisiRoute: PcStatusPengajuanTicketIdRevisiRoute,
  }

const PcStatusPengajuanTicketIdRouteWithChildren =
  PcStatusPengajuanTicketIdRoute._addFileChildren(
    PcStatusPengajuanTicketIdRouteChildren,
  )

interface PcRouteChildren {
  PcDaftarkanRoute: typeof PcDaftarkanRoute
  PcNotificationsRoute: typeof PcNotificationsRoute
  PcIndexRoute: typeof PcIndexRoute
  PcStatusPengajuanTicketIdRoute: typeof PcStatusPengajuanTicketIdRouteWithChildren
  PcStatusPengajuanIndexRoute: typeof PcStatusPengajuanIndexRoute
}

const PcRouteChildren: PcRouteChildren = {
  PcDaftarkanRoute: PcDaftarkanRoute,
  PcNotificationsRoute: PcNotificationsRoute,
  PcIndexRoute: PcIndexRoute,
  PcStatusPengajuanTicketIdRoute: PcStatusPengajuanTicketIdRouteWithChildren,
  PcStatusPengajuanIndexRoute: PcStatusPengajuanIndexRoute,
}

const PcRouteWithChildren = PcRoute._addFileChildren(PcRouteChildren)

interface PwStatusPengajuanTicketIdRouteChildren {
  PwStatusPengajuanTicketIdRevisiRoute: typeof PwStatusPengajuanTicketIdRevisiRoute
}

const PwStatusPengajuanTicketIdRouteChildren: PwStatusPengajuanTicketIdRouteChildren =
  {
    PwStatusPengajuanTicketIdRevisiRoute: PwStatusPengajuanTicketIdRevisiRoute,
  }

const PwStatusPengajuanTicketIdRouteWithChildren =
  PwStatusPengajuanTicketIdRoute._addFileChildren(
    PwStatusPengajuanTicketIdRouteChildren,
  )

interface PwRouteChildren {
  PwDaftarkanRoute: typeof PwDaftarkanRoute
  PwNotificationsRoute: typeof PwNotificationsRoute
  PwIndexRoute: typeof PwIndexRoute
  PwStatusPengajuanTicketIdRoute: typeof PwStatusPengajuanTicketIdRouteWithChildren
  PwStatusPengajuanIndexRoute: typeof PwStatusPengajuanIndexRoute
}

const PwRouteChildren: PwRouteChildren = {
  PwDaftarkanRoute: PwDaftarkanRoute,
  PwNotificationsRoute: PwNotificationsRoute,
  PwIndexRoute: PwIndexRoute,
  PwStatusPengajuanTicketIdRoute: PwStatusPengajuanTicketIdRouteWithChildren,
  PwStatusPengajuanIndexRoute: PwStatusPengajuanIndexRoute,
}

const PwRouteWithChildren = PwRoute._addFileChildren(PwRouteChildren)

interface ReviewInboxRouteChildren {
  ReviewInboxTicketIdRoute: typeof ReviewInboxTicketIdRoute
}

const ReviewInboxRouteChildren: ReviewInboxRouteChildren = {
  ReviewInboxTicketIdRoute: ReviewInboxTicketIdRoute,
}

const ReviewInboxRouteWithChildren = ReviewInboxRoute._addFileChildren(
  ReviewInboxRouteChildren,
)

interface ReviewRouteChildren {
  ReviewAuditLogRoute: typeof ReviewAuditLogRoute
  ReviewInboxRoute: typeof ReviewInboxRouteWithChildren
  ReviewNotificationsRoute: typeof ReviewNotificationsRoute
  ReviewPeruriRoute: typeof ReviewPeruriRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewAuditLogRoute: ReviewAuditLogRoute,
  ReviewInboxRoute: ReviewInboxRouteWithChildren,
  ReviewNotificationsRoute: ReviewNotificationsRoute,
  ReviewPeruriRoute: ReviewPeruriRoute,
  ReviewIndexRoute: ReviewIndexRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

interface StatusTicketIdRouteChildren {
  StatusTicketIdRevisiRoute: typeof StatusTicketIdRevisiRoute
}

const StatusTicketIdRouteChildren: StatusTicketIdRouteChildren = {
  StatusTicketIdRevisiRoute: StatusTicketIdRevisiRoute,
}

const StatusTicketIdRouteWithChildren = StatusTicketIdRoute._addFileChildren(
  StatusTicketIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AktivasiRoute: AktivasiRouteWithChildren,
  CekStatusRoute: CekStatusRoute,
  KodeAksesRoute: KodeAksesRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRouteWithChildren,
  PcRoute: PcRouteWithChildren,
  PwRoute: PwRouteWithChildren,
  ReviewRoute: ReviewRouteWithChildren,
  StatusTicketIdRoute: StatusTicketIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
